### ISSUE TITLE
KV binding not working

### ISSUE THREAD

**Issue by IAMSDR** [yjl9903/vite-plugin-cloudflare-functions#273]
### Describe the bug

my vite config

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import CloudflarePagesFunctions from 'vite-plugin-cloudflare-functions';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    CloudflarePagesFunctions({
      wrangler: {
        binding: {
          USERNAME: "user",
          PASSWORD: "pass"
        },
        log: true,
        kv: [
          { 
            binding : "KV_STORE",
            id: "ab52dbc074ec464a9d98552d7b87xxxxxx",
            preview_id: "9683a02854f24c84ac91089xxxxxxx"
          }
        ]
      }
    })
  ],
})
```

and a post method

```import { makePagesFunction, makeResponse } from 'vite-plugin-cloudflare-functions/worker';

export const onRequestPost = makePagesFunction(async ({ env, request}) => {

    let data = await request.json();
    env.KV_STORE.put('test', JSON.stringify(data));

    return makeResponse({msg: 'Data saved !!'},{ status: 200 });
})
```

throws error
```TypeError: Cannot read properties of undefined (reading 'put')```

logging env
console.log(env)
returns

```
{
  '[object': KVNamespace {},
  'Object]': KVNamespace {},
  ASSETS: Fetcher {},
  USERNAME: 'user',
  PASSWORD: 'pass'
}
```

### Reproduction

kv binding

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i5-12500H
    Memory: 8.25 GB / 15.63 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

**Comment by yjl9903** [comment]
In the vite config, kv only supports a single string or a string arry config (see https://github.com/yjl9903/vite-plugin-cloudflare-functions/blob/e9ca8e2b8e0d8617ce22653e6ff7fa03b500d88a/packages/vite-plugin-cloudflare-functions/src/vite/types.ts#L49-L52 and https://github.com/yjl9903/vite-plugin-cloudflare-functions/blob/e9ca8e2b8e0d8617ce22653e6ff7fa03b500d88a/packages/vite-plugin-cloudflare-functions/src/vite/index.ts#L55-L63).

I think you only need to use `{ kv: ['KV_STORE'] }` to binding kv namespace here.

**Comment by yjl9903** [comment]
According to their document https://developers.cloudflare.com/pages/platform/functions/bindings/#kv-namespaces

I think you should set your kv namespace id in the cf pages dashboard in production.

When develop locally, you only need to config the kv namespace name to make local kv namespace dev work.

**Comment by yjl9903** [comment]
I have updated the README document to provide a more clear example and its explaination. Could you check it please?

**Comment by IAMSDR** [comment]
Thanks for quick reply , 
It's doesn't require any id binding to work in local dev mode.
it's creating local kv store under ```/functions/.wrangler/state/kv ``` folder.
Thank u 😊
