### ISSUE TITLE
What's the right way of using KV with vite-plugin-cloudflare-functions?

### ISSUE THREAD

**Issue by hellodword** [yjl9903/vite-plugin-cloudflare-functions#457]
- The demo `https://vite-plugin-cloudflare-functions.pages.dev/api/state/key1`  will get `Error 1101`
- I created a [minimal repo](https://github.com/hellodword/vite-plugin-cloudflare-functions-playground/tree/minimal) from the [playground](https://github.com/yjl9903/vite-plugin-cloudflare-functions/tree/main/playground), the `vite` works well locally, but same error with deployments.

```sh
$ curl https://<...>.pages.dev/api/world
{"status":"OK","data":"Hello, world!","env":{"...

$ curl https://<...>.pages.dev/api/state/key1
Error 1101
```

```sh
# verify the api token and the KV namespace
$ wrangler kv:key --namespace-id <...> put key1 val1
$ wrangler kv:key --namespace-id <...> get key1
val1
```

The `wrangler.toml`:

```toml
name = "playground"
workers_dev = true
send_metrics = false
logpush = false
kv_namespaces = [
  { binding = "KV_STORE", id = "<...>" }
]
```

**Comment by yjl9903** [comment]
For production, I am not sure whether pages function support use `wrangler.toml`.

I think you should config it on the cloudflare dashboard, like the following picture (KV Namespace binding section)

![image](https://github.com/yjl9903/vite-plugin-cloudflare-functions/assets/30072175/aa3b7fa4-ddf2-4036-9f29-6521955a207a)

And you can check whether the binding is working for a deploy.

![image](https://github.com/yjl9903/vite-plugin-cloudflare-functions/assets/30072175/976433ba-4215-48c8-87e0-3df10e797c5c)
