### ISSUE TITLE
Allow disable dts generation

### ISSUE THREAD

**Issue by Tsuk1ko** [yjl9903/vite-plugin-cloudflare-functions#691]
### Clear and concise description of the problem

For some reason, I don't need the `cloudflare.d.ts` file and I hope to disable the output.

### Suggested solution

I think if `dts` is explicitly specified as `false` in the configuration, the output can be disabled.

https://github.com/yjl9903/vite-plugin-cloudflare-functions/blob/6c74b11b086d5d4a2804daa6eba31830a56abc01/packages/vite-plugin-cloudflare-functions/src/vite/index.ts#L50-L52

Change to

```ts
if (typeof userConfig.dts !== 'boolean' && typeof userConfig.dts !== 'string') {
  userConfig.dts = true;
}
```

**Comment by yjl9903** [comment]
Fixed in https://github.com/yjl9903/vite-plugin-cloudflare-functions/commit/9a65cb67aef7e18f5d890eb96c2b01073592d4a4
