### ISSUE TITLE
Change --persist-to-directory or make configurable

### ISSUE THREAD

**Issue by dirksierd** [yjl9903/vite-plugin-cloudflare-functions#798]
### Describe the bug

This plugin is great, thanks a lot for it!
Here's a thing that bugs me a bit though…

Wrangler tends to default its state directory to .wrangler/state on the root-level of the project.
This plugin, though, wants the state-directory to be in the functions-directory instead.

For example… I like to use D1 a lot, and this is what I'm running into now:

- When running wrangler d1 migrate (…) it says there's no migrations left (because in the default state-directory, at the root of my project, these tables exist)
- When starting the server, it can't find those tables, though, because the plugin looks in another directory

Is this something to reconsider? I don't believe I can set wrangler to look in the functions-root-directory instead.

<https://github.com/yjl9903/vite-plugin-cloudflare-functions/blob/4118a99fd3d9f016e0ccf6e280bea467ad8e672b/packages/vite-plugin-cloudflare-functions/src/vite/index.ts#L136>

### System Info

```Shell
System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M2
    Memory: 94.61 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.asdf/installs/nodejs/20.10.0/bin/node
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Safari: 18.2
```

### Used Package Manager

npm

**Comment by dirksierd** [comment]
Update: I've now discovered that it is possible to run the D1 migration-commands, for example, against a different --persist-to-directory. This fixes the problem for now, but it is a bit bothersome.

**Comment by yjl9903** [comment]
I will check it and make it configurable this days.

**Comment by yjl9903** [comment]
https://github.com/yjl9903/vite-plugin-cloudflare-functions/commit/1a37bb7d68b99820dd4bbea07baa275d8516eb33
